[package]
name = "exspheriment"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0"
bevy = "0.7"
bytemuck = { version = "1.9", features = ["derive"] }

[profile.dev]
opt-level = 3